// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.alican.grpcHelloWorld.proto_gen.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alican.grpcHelloWorld.proto_gen.hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>repeated string strings = 3;</code>
   */
  java.util.List<java.lang.String>
      getStringsList();
  /**
   * <code>repeated string strings = 3;</code>
   */
  int getStringsCount();
  /**
   * <code>repeated string strings = 3;</code>
   */
  java.lang.String getStrings(int index);
  /**
   * <code>repeated string strings = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringsBytes(int index);

  /**
   * <code>map&lt;string, int32&gt; map = 4;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, int32&gt; map = 4;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getMap();
  /**
   * <code>map&lt;string, int32&gt; map = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getMapMap();
  /**
   * <code>map&lt;string, int32&gt; map = 4;</code>
   */

  int getMapOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; map = 4;</code>
   */

  int getMapOrThrow(
      java.lang.String key);
}
