// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.alican.grpcHelloWorld.proto_gen.hello;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022)com.alican.grpcHel" +
      "loWorld.proto_gen.hello\032\033google/protobuf" +
      "/empty.proto\032\037google/protobuf/timestamp." +
      "proto\"\277\001\n\014HelloRequest\022\021\n\tfirstName\030\001 \001(" +
      "\t\022\020\n\010lastName\030\002 \001(\t\022\017\n\007strings\030\003 \003(\t\022M\n\003" +
      "map\030\004 \003(\0132@.com.alican.grpcHelloWorld.pr" +
      "oto_gen.hello.HelloRequest.MapEntry\032*\n\010M" +
      "apEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"" +
      "R\n\rHelloResponse\022\020\n\010greeting\030\001 \001(\t\022/\n\013cr" +
      "eatedDate\030\002 \001(\0132\032.google.protobuf.Timest",
      "amp2\215\003\n\014HelloService\022\203\001\n\014ExecuteHello\0227." +
      "com.alican.grpcHelloWorld.proto_gen.hell" +
      "o.HelloRequest\0328.com.alican.grpcHelloWor" +
      "ld.proto_gen.hello.HelloResponse\"\000\022\215\001\n\022E" +
      "xecuteHelloStream\0227.com.alican.grpcHello" +
      "World.proto_gen.hello.HelloRequest\0328.com" +
      ".alican.grpcHelloWorld.proto_gen.hello.H" +
      "elloResponse\"\000(\0010\001\022g\n\021ExecuteHelloEmpty\022" +
      "\026.google.protobuf.Empty\0328.com.alican.grp" +
      "cHelloWorld.proto_gen.hello.HelloRespons",
      "e\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Strings", "Map", });
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_MapEntry_descriptor =
      internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloRequest_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alican_grpcHelloWorld_proto_gen_hello_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", "CreatedDate", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
