// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.alican.grpcHelloWorld.proto_gen.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alican.grpcHelloWorld.proto_gen.hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();

  /**
   * <code>.google.protobuf.Timestamp createdDate = 2;</code>
   */
  boolean hasCreatedDate();
  /**
   * <code>.google.protobuf.Timestamp createdDate = 2;</code>
   */
  com.google.protobuf.Timestamp getCreatedDate();
  /**
   * <code>.google.protobuf.Timestamp createdDate = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder();
}
